<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 '. $this->translate('Diamonds Design'))->setSeparator(' - ')->setAutoEscape(false) ?>
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/png', 'href' => $this->basePath() . '/assets/ico/favicon.png'))
                        ->prependStylesheet($this->basePath() . '/assets/css/style.css')
						//->prependStylesheet($this->basePath() . '/assets/css/bootstrap-responsive.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/bootstrap.css') ?>

	    <style>
	      body {
	        padding-top: 80px; /* 60px to make the container go all the way to the bottom of the topbar */
	      }
	    </style>
	                     
    </head>
    <body>
        	
    	<?php echo $this->partial('layout/navigation'); ?>

		<?php echo $this->content; ?>
	
	    <footer>
	    	<div class="container">
	    		<nav>
					<ul class="footer-nav">
						<li><a href="/">Home</a></li>
		                <li><a href="/about-us">About Us</a></li>
		                <li><a href="/products">Products</a></li>
		                <li><a href="/marketing-plan">Marketing Plan</a></li>
		                <li><a href="/promos">Promos</a></li>
		                <li><a href="/gem-of-idea">Gem Of Idea</a></li>
		                <li><a href="/manufacturer">Manufacturer</a></li>
		                <li><a href="/contact-us">Contact Us</a></li>
					</ul>
	    		</nav>
	       		<div class="text-muted text-center">&copy Copyright 2013 Diamonds-Designs. All Rights Reserved.</div>
	       		<p>Everything written on this site and any image that is in an article, is licensed under a Diamonds-Designs.com license as long as I'm the author of the material.</p>
	        </div>
	    </footer>

	    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
	    <!--[if lt IE 9]>
	      <script src="/assets/js/html5shiv.js"></script>
	    <![endif]-->
	    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
	    <script src="/assets/js/bootstrap.min.js"></script>
		
        <?php echo $this->inlineScript() ?>

    </body>
</html>
