    <div class="navbar navbar-inverse navbar-fixed-top">
      	<div class="navbar-inner">
			<a href="/" class="brand"><img src="/assets/img/logo.png" title="Diamonds Design" alt="" /></a>
			<div class="nav-collapse collapse">
				<ul class="nav">
	                <li><a href="/about-us">About Us</a></li>
	                <li><a href="/products">Products</a></li>
	                <li><a href="/marketing-plan">Marketing Plan</a></li>
	                <li><a href="/promos">Promos</a></li>
	                <li><a href="/gem-of-idea">Gem Of Idea</a></li>
	                <li><a href="/manufacturer">Manufacturer</a></li>
	                <li><a href="/contact-us">Contact Us</a></li>
				</ul>
			</div>
      	</div>
    </div>