<?php
$title = 'About Us';
$this->headTitle($title);
//$this->headLink()->appendStylesheet($this->basePath() . '/assets/css/style1.css');
//$this->inlineScript()->appendFile($this->basePath() . '/assets/js/inner.js', 'text/javascript');
//$this->inlineScript()->appendFile($this->basePath() . '/assets/js/module/zendesk.js')

echo $this->partial('layout/navigation');
?>

	<section class="container">
      	<article class="text-center">
			<h1><center>About Us</center></h1>
			<hr />
			<h3 class="text-center">Company Profile</h3>
			<p class="text-center">Diamonds n Designs committed to provide quality jewelries with trendy and unique designs that will entice even your most selective clientele.</span></p>
			<h3 class="text-center">Company Mission</h3> 
			<p class="text-center">Aims to produce more entrepreneur; creates a rewarding business that boost lifestyle of every deserving individual.</p>
			<h3 class="text-center">Company Vision</h3> 
			<p class="text-center">We commit ourselves to building a good name in the industry with God's grace and guidance.</p>
		    <h3 class="text-center">Corporate Social Responsibility</h3>
			<p class="text-center">Building on this core value of providing opportunities, best exemplified by its core manufactures to serve as the company's social responsibility arm. Diamonds n Designs has been carrying out its mission through the 
		     generous support provided by the member manufacturers through projects that effectively create opportunities. Diamonds n Designs aims to empower people with the ability to enhance their options in life.</p>

     	</article>
    </section>
