<?php
$title = 'Diamonds Design';
$this->headTitle($title);
//$this->inlineScript()->appendFile($this->basePath() .  '/assets/js/bootstrap-carousel.js');
//$this->inlineScript()->appendFile($this->basePath() .  '/assets/js/waypoint/jquery.scrollTo-1.4.2-min.js');

?>


	<div class="row">
		<div class="splash-features">
			<img src="/assets/img/home-main-5.jpg" title="" />
		</div>
	</div>

	<section class="container">
      	<article class="featurette text-center">
        	<h2 class="featurette-heading">Diamonds n Designs <span class="muted">all beautifully designed for YOU!</span></h2>
        	<p class="lead">
	      		Today, Women across age groups have begun to realize the many potentials of Gold Jewelry - either as simple yet elegant jewels to spice up wardrobe and complete your outlook, as a heirloom to be passed on to generations, or as an alternative investment to build one's wealth.
        	</p>
		    <p class="lead">
		      	Diamonds n Designs introduces in the country the innovative way and rewarding concept in jewelry selling. Thus, takes a step further by incorporating precious diamond stones set in the gold which allows every woman to unleash the jewelry lover in her.
		    </p>
		    <p class="lead">
		      	At Diamonds n Designs, gold will no longer be just a statement of personal style. It will be a statement of good judgment. 
		    </p>
	    	<p class="lead"><strong>Because it's not just about jewels. It's about YOU investing and building your own wealth.</strong></p>
     	</article>
	  	<figure class="container">
			<hr class="featurette-divider">
			<h3 class="text-center">We will help you to find best ever Diamonds. <a href="/products/" class="btn btn-large btn-warning" title="Product">Find More Collections</a></h3> 
	  	</figure>
    </section>

