<?php
$title = 'Manufacturer';
$this->headTitle($title);
//$this->headLink()->appendStylesheet($this->basePath() . '/assets/css/style1.css');
//$this->inlineScript()->appendFile($this->basePath() . '/assets/js/inner.js', 'text/javascript');
//$this->inlineScript()->appendFile($this->basePath() . '/assets/js/module/zendesk.js')

echo $this->partial('layout/navigation');
?>

	<div class="container">
		<div class="row-fluid">
			<h2><center>Manufacturer</center></h2>
		    <hr />
		    <section class="container">
		        <div class="row-fluid">
			     <center>
		                <img src="/assets/img/live_diamonds1.jpg" >
		            </center> 
			     <p>&nbsp;</p>           
		            <p class="lead text-center">Diamonds n Designs is equipped with top leading manufactures in the world. They are working energetically and striving to upgrade for the increasingly intensive competition and challenges in the business world. Looking towards the future, We always seek improvement not just the highest quality of its product we produce but in all aspects of the business as well.</p>
			     <p>&nbsp;</p>
			     <center>
		                <img src="/assets/img/live_diamonds.jpg" > 
		            </center> 
		        </div>
		    </section>   
		</div>
	</div>