<?php
$title = 'Marketing Plan';
$this->headTitle($title);
//$this->headLink()->appendStylesheet($this->basePath() . '/assets/css/style1.css');
//$this->inlineScript()->appendFile($this->basePath() . '/assets/js/inner.js', 'text/javascript');
//$this->inlineScript()->appendFile($this->basePath() . '/assets/js/module/zendesk.js')

echo $this->partial('layout/navigation');
?>

	<div class="container">
		<div class="row-fluid">
	      	<div class="span10 offset1">
	  			<h2><center>Ways To Earn</center></h2>
	      		<div class="row-fluid well">
					<hgroup class="span6">
			        	<h3>Regular Items</h3>
						<ul class="unstyled">
							<li class="lead-check"><i class="icon-ok"></i> Direct Selling -  25% discount</li>
							<li class="lead-check"><i class="icon-ok"></i> Direct Referral/ 1st Level - earn 10% cash from 1st level purchase.</li>
							<li class="lead-check"><i class="icon-ok"></i> In-Direct Referral / 2nd Level - earn 2% cash from 2nd level purchase.</li>
						</ul>
					</hgroup>
					<hgroup class="span6">
			        	<h3>Sale Items</h3>
						<ul class="unstyled">
							<li class="lead-check"><i class="icon-ok"></i> Direct Selling -  5% discount</li>
							<li class="lead-check"><i class="icon-ok"></i> Direct Referral/ 1st Level - earn 2% cash from 1st level purchase.</li>
							<li class="lead-check"><i class="icon-ok"></i> In-Direct Referral / 2nd Level - earn 2% cash from 2nd level purchase.</li>
						</ul>
					</hgroup>
					<p class="text-info text-center lead"><strong>SPECIAL PROMO</strong> - No discount, No upline rebates but counted in Sales quota. </p>
				</div>
			</div>
		</div>
			
		<hr />
		<div class="row-fluid">
			<div class="span6 offset3">
				<h2 class="text-center">How To Qualify For Incentives</h2>
				
				<table class="table table-hover">
					<tbody>
						<tr>
							<td class="lead-check"><i class="icon-tasks"></i> Personal Purchase/Net Sales</td>
						</tr>
						<tr>
							<td class="lead-check"><i class="icon-tasks"></i> Recruitment/Referral</td>
						</tr>
						<tr>
							<td class="lead-check"><i class="icon-tasks"></i> Group Sales (65% of the total FIRST LEVEL net sales for Non Qualifiers will be added to your personal sales)</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>	
		<hr />
		<div class="row-fluid">
			<p class="text-info text-center lead"><strong>PROMOTION RANK</strong> for Downline Qualifiers</p>
			<article class="text-center">
				<h4>Team Leader</h4>
				<div class="span6 offset3">
	                <table class="table table-bordered">
						<tbody>
							<tr>
								<td class="lead-check"><i class="icon-chevron-right"></i> Must be a qualifier (travel) for any promo at given period.</td>
							</tr>
							<tr>
								<td class="lead-check"><i class="icon-chevron-right"></i>  Must have at least 1 qualifier (travel) in four different legs up to 5th level.</td>
							</tr>
						</tbody>
					</table>
				</div>
		
				<div class="span6 offset3">				
					<h4>Incentives for Team Leader</h4>
						<table class="table table-bordered">
						<tbody>
							<tr>
								<td class="lead-check"><i class="icon-chevron-right"></i> Free 1 travel ( depends on the majority of your group travel incentives )</td>
							</tr>
							<tr>
								<td class="lead-check"><i class="icon-chevron-right"></i>  Leadership Incentive ( varies depending on the promo )</td>
							</tr>
							<tr>
								<td class="lead-check"><i class="icon-chevron-right"></i>  Jewelry Gift</td>
							</tr>
						</tbody>
					</table>
				</div>
			</article>
			
		</div>
		<div class="row-fluid">	
			<article class="text-center">
				<h4>Executive Team Leader</h4>
					<div class="span6 offset3">
		                <table class="table table-bordered">
							<tbody>
								<tr>
									<td class="lead-check"><i class="icon-chevron-right"></i> Must be a qualifier (travel) for any promo at given period.</td>
								</tr>
								<tr>
									<td class="lead-check"><i class="icon-chevron-right"></i>  Must have at least 1 qualifier (travel) in eight different legs up to 5th level.</td>
								</tr>
							</tbody>
						</table>
					</div>
					
					<div class="span6 offset3">
						<h4>Incentives for Executive Team Leader</h4>
		                <table class="table table-bordered">
							<tbody>
								<tr>
									<td class="lead-check"><i class="icon-chevron-right"></i> Free 2 travels ( depends on the majority of your group travel incentives )</td>
								</tr>
								<tr>
									<td class="lead-check"><i class="icon-chevron-right"></i>  Leadership Incentive ( double the amount from Team Leader L.I )</td>
								</tr>
								<tr>
									<td class="lead-check"><i class="icon-chevron-right"></i>  Jewelry Gift</td>
								</tr>
							</tbody>
						</table>
					</div>
			</article>
		</div>
		<div class="row-fluid">	
			<hr />
			<div class="text-center">
				<h3>Purchase Requirement To Earn Rebates</h3>
				<p class="lead-check text-info">Purchase of P100,000 with in the promo period.</p>
			</div>
	<hr />
			<hgroup class="text-center">
				<h4>AWARDS:</h4>
				<p class="lead-check">GOLD AWARDEE - FOR  SINGLE TRAVEL QUALIFIER</p>
				<p class="lead-check">DIAMOND AWARDEE - FOR COUPLE TRAVEL QUALIFIERS</p>
			</hgroup>
	
		
		</div>
		
	</div>
