<?php
$title = 'Promos & Incentives';
$this->headTitle($title);
//$this->headLink()->appendStylesheet($this->basePath() . '/assets/css/style1.css');
//$this->inlineScript()->appendFile($this->basePath() . '/assets/js/inner.js', 'text/javascript');
//$this->inlineScript()->appendFile($this->basePath() . '/assets/js/module/zendesk.js')

echo $this->partial('layout/navigation');
?>

	<div class="container">
		<div class="row-fluid">
			
			<h1><center>Promos & Incentives</center></h1>
				
				<hr />
				<section class="promos-container">
					<div class="row-fluid">
						<div class="span6 offset3">
							<h3>Trip to Europe</h3>
					    	<table class="table table-hover">
					    		<tbody>
					    			<tr>
					    				<td><strong>Travel Month</stron></td>
					    				<td>April 2014</td>
						    		</tr>
						    		<tr>
					    				<td><strong>Period</stron></td>
					    				<td>April 2013 to March 2014</td>
						    		</tr>
						    		<tr>
					    				<td><strong>Duration</stron></td>
					    				<td>12 Months</td>
						    		</tr>
						    		<tr>
					    				<td><strong>Sales Quota</stron></td>
					    				<td>975,000</td>
						    		</tr>
					    		</tbody>
					    	</table>
					    	<img src="/assets/img/promo-europe.jpg" title="Trip to Europe" alt="" />
			    		</div>
			    	</div>
				</section>
				<hr />
				<section class="promos-container">
					<div class="row-fluid">
						<div class="span6 offset3">
							<h3>Trip to Japan</h3>
					    	<table class="table table-hover">
					    		<tbody>
					    			<tr>
					    				<td><strong>Travel Month</strong></td>
						    			<td>October 2014</td>
						    		</tr>
						    		<tr>
					    				<td><strong>Period<strong></td>
						    			<td>September 2013 to August 2014</td>
						    		</tr>
						    		<tr>
					    				<td><strong>Duration<strong></td>
						    			<td>12 Months</td>
						    		</tr>
						    		<tr>
					    				<td><strong>Sales Quota<strong></td>
						    			<td>487,500</td>
						    		</tr>
					    		</tbody>
					    	</table>
					    	<img src="/assets/img/promo-japan.jpg" title="Trip to Japan" alt="" />
						</div>	
			    	</div>
				</section>	      	
		
		</div>
		
	</div>

